version: '3'
services:
  
  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - '4444:4444'
    networks:
      - selenium-network

  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile.scraper
    volumes:
      - ./scrapers:/app
    depends_on:
      - selenium
    networks:
      - selenium-network
    
networks:
  selenium-network:
    driver: bridge